version: '3'

services:
  postgres-local:
    container_name: postgres-local    
    platform: linux/amd64
    image: postgres:17.7-alpine3.22
    restart: always
    ports:
      - '5437:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-local-data:/var/lib/postgresql/data
  
volumes:
  postgres-local-data:
